### ISSUE TITLE
color: 'auto' is bad on windows

### ISSUE THREAD

**Issue by Nama** [your-tools/python-cli-ui#51]
I developed the whole time on PyCharm and tested on Windows Terminal. The colors are working fine on those. But not on cmd, Windows Powershell and Powershell Core.
That means, if I run cmd (or any PS) in Windows Terminal, the colors work.

I'd like to keep them, but well, the best option would be to set the default instead of 'auto' to 'never' on Windows...

Edit:
By "not working", I mean it like this:
```
[1m[34m:: [0mNo config found. Creating new one.
[0m[1m[34m* [0mNothing's deleted if you cancel now.
[0m[1m[34m=> [0mWe need to give all sensors a name, so you can recognize them.
[0mCheck the sensors in LHM first, to know them: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
[0m[1m[34m:: [0mI set the speed to 100% for 5 seconds
[0m[1m[34m=> [0mHardware string: /lpc/nct6795d/control/0
[0m[32m:: [0mName this sensor: Fan Control #1 [0m(Fan Control #1)
```
It's very hard to read.

**Comment by dmerejkowsky** [comment]
> the best option would be to set the default instead of 'auto' to 'never' on Windows...

That would be sad :/ I mostly use cli-ui on cmd.exe or mingw on windows, and I would miss not having colors there (at least by default)

That being said, we could also implement https://bixense.com/clicolors/ so that Windows users could opt in to have colors.

Finally, maybe it's a bug with colorama? cli-ui kind of trusts colorama.init() to do the right thing, so you might want to check if there's a bug to be open downstream.

**Comment by Nama** [comment]
Wait, colors work for you in cmd? oO

**Comment by dmerejkowsky** [comment]
You're right - there's a bug. It is supposed to work on cmd.exe but it does not. I'll investigate.

**Comment by dmerejkowsky** [comment]
> Wait, colors work for you in cmd? oO

Well, it works when using `colorama==0.4.3` on my machine.

I did found on bug, though:

```python
 def config_color(fileobj: FileObj) -> bool:
   ...
    if os.name == "nt":
        # sys.isatty() is False on mintty, but we want colors by default
        return True
```

That was a bad idea because it means that if `colorama` does the wrong thing, you get garbage in the output.

So I removed this workaround.

This means that now, by default, colors will be off when using mintty, but since I've _also_ implemented the [clicolors](https://bixense.com/clicolors/), mintty users can opt-in for color support by setting `CLICOLORS_FORCE=1`

I think it's a good compromise.

Tell me what you think!

**Comment by Nama** [comment]
I've over read, that colorama is optional...
Still, I can't make colors work. I installed `colorama` and `unidecode`. Later I initialized colorama manually, but still no colors.
```python
from colorama import init
init()
```

![grafik](https://user-images.githubusercontent.com/2297270/85848908-4f3de080-b7aa-11ea-9d72-983310544bb6.png)



> I think it's a good compromise.

If clicolors is also optional, yes, that sounds good.

**Comment by dmerejkowsky** [comment]
> I've over read, that colorama is optional...

You may have been misled by some outdated documentation - sorry about that - colorama is no longer an optional dependency.

> Still, I can't make colors work

Hum. I can't reproduce this behavior here.  Can you share relevant parts of the `ui.py` script and the name of the console you're using ?

> If clicolors is also optional, yes, that sounds good.

It's not an additional dependency, it's just that `cli-ui` will read some environment variables to enable color support once #52 is merged.

**Comment by Nama** [comment]
> You may have been misled by some outdated documentation - sorry about that - colorama is no longer an optional dependency.

Strange, colorama and unidecode weren't installed automatically as dependency.

> Hum. I can't reproduce this behavior here. Can you share relevant parts of the `ui.py` script and the name of the console you're using ?

That's producing the garbage output. On Powershell and cmd.
```python
import cli_ui as ui
choices = {'Add new rule': 'add', 'List Hardware Sensors': 'list_sensors', 'List Config Rules': 'list_config', 'Remove one rule': 'remove', 'Stop controlling the fans': 'stop', 'Reset your config': 'reset', 'Exit': 'exit'}
pick = ui.ask_choice('Interactive Mode. Use --daemon after setting up.', choices=list(choices.keys()), sort=False)
```

**Comment by dmerejkowsky** [comment]
> Strange, colorama and unidecode weren't installed automatically as dependency.

That's weird. How did you install cli-ui ?

**Comment by Nama** [comment]
With PyCharm, which uses pip and pypi?
Just did a new venv and it worked. No idea what I fucked up... (colors are still broken on the new venv)
```
pip install cli-ui
Collecting cli-ui
  Using cached cli_ui-0.10.3-py3-none-any.whl (11 kB)
Collecting unidecode<2.0.0,>=1.0.23
  Using cached Unidecode-1.1.1-py2.py3-none-any.whl (238 kB)
Collecting tabulate<0.9.0,>=0.8.3
  Using cached tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting colorama<0.5.0,>=0.4.1
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Installing collected packages: unidecode, tabulate, colorama, cli-ui
Successfully installed cli-ui-0.10.3 colorama-0.4.3 tabulate-0.8.7 unidecode-1.1.1
```

**Comment by dmerejkowsky** [comment]
> no idea what I fucked up... (colors are still broken on the new venv)

I think that's the bug I've fixed. I can make a beta release so it's easier for you to test it

**Comment by Nama** [comment]
Did you do a version tick?
Installing from dm/colorful-fixes didn't fix the colors.

As you can see in my screenshot above, git is able to display colors. I will test on other machines, too.

**Comment by Nama** [comment]
Ya, just tested on another machine with Python 3.8, a fresh venv and on the new branch. Color output is broken like in my first post and screenshot.
Only works in Windows Terminal, but not in cmd and PS (without Windows Terminal).
So, building to an exe with PyInstaller has the same problem.

**Comment by dmerejkowsky** [comment]
Interesting. Can you check using `colorama` only ?

```python
import colorama

colorama.init()
print(colorama.Fore.RED, "this is red")
```

**Comment by Nama** [comment]
works in Powershell and cmd. Same venv.
![grafik](https://user-images.githubusercontent.com/2297270/86045260-a1e9f780-ba4b-11ea-92b4-a077f1f01d06.png)

**Comment by dmerejkowsky** [comment]
I'm not sure what's going on here. It seems like `colorama.init()` was never called.

Can you double-check that you are using the dm/colorful-fixes branch?

You can also add print statements in cli_ui's source code, like in the `_init_colorama()` function.

**Comment by Nama** [comment]
I've put some prints, they are all printed.
```py
def _init_colorama() -> None:
    global _INITIALIZED
    if not _INITIALIZED:
        colorama.init()
        print(colorama.Fore.RED, '_INITIALIZED')
        _INITIALIZED = True
```
This color is working.  But no colors from cli_ui, the color codes are printed.
```py
_init_colorama()
print('def message')
```
```py
class Color:
    """Represent an ANSI escape sequence """

    def __init__(self, code: str):
        self.code = code
        print('class Color')
```
![grafik](https://user-images.githubusercontent.com/2297270/86174517-142d0b80-bb22-11ea-89c0-239a62363eff.png)

**Comment by dmerejkowsky** [comment]
I still have no clue about why this is happening - and I'm still unable to reproduce the issue :/

What is exactly the version of Windows you are using? (can you add a screenshot of the `winver` command?) Ditto for the powershell version.

This is a long shot, but can you try if this works?

```python
import sys
import colorama
colorama.init()
print(colorama.Fore.RED + 'this is red' + colorama.Style.RESET_ALL)  # note the '+'
sys.stdout.write(colorama.Fore.BLUE + 'this is blue' + colorama.Style.RESET_ALL)
sys.stdout.flush()
```

**Comment by Nama** [comment]
> I still have no clue about why this is happening - and I'm still unable to reproduce the issue :/

Ya it is. You tried outside of Windows Terminal, right?

> This is a long shot, but can you try if this works?

Yes, it works on all terminals
![grafik](https://user-images.githubusercontent.com/2297270/86512736-f05d1480-be04-11ea-91e2-9dd53b88dddb.png)

> What is exactly the version of Windows you are using? (can you add a screenshot of the `winver` command?) Ditto for the powershell version.

Powershell Core: 7.0.2
Windows Powershell: 5.1.18362.752
Windows: 10.0.18363.900
![grafik](https://user-images.githubusercontent.com/2297270/86512778-547fd880-be05-11ea-8a3b-4b0a519a672d.png)

**Comment by dmerejkowsky** [comment]
Can you  please retry with version 0.14.0 that was just released?

**Comment by Nama** [comment]
Yes, it works now! On all three terminals. I had to set `color='always'`. (but I guess you did that cause it didn't work, right?)
Thank you!
![grafik](https://user-images.githubusercontent.com/2297270/115422626-5f252600-a1fd-11eb-9c29-0233a8ce94c3.png)

**Comment by dmerejkowsky** [comment]
> I guess you did that cause it didn't work, right?)

Yes, exactly

> Thank you

You´re welcome.

The bad news is that cli_ui is now broken on Linux :P I´ll fix that in a later release ...
